---
- name: install dependencies
  when: ansible_os_family == "Debian"
  apt: update_cache=yes name={{ item }} state=present
  with_items:
    - python-dev
    - libbz2-dev
  
- name: install Boost 1.57.0
  shell: |
    creates=/usr/include/boost
    cd
    wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz
    tar xvf boost_1_57_0.tar.gz
    cd boost_1_57_0
    ./bootstrap.sh --with-toolset=clang --prefix=/usr
    ./b2 install \
      toolset=clang \
      cxxflags="-std=gnu++14 -stdlib=libc++" \
      linkflags="-stdlib=libc++" \
      --prefix=/usr \
      -j 2
    cd
    rm -rf boost_1_57_0*
