---
- name: add apt repository
  when: ansible_os_family == "Debian"
  apt_repository: repo=ppa:ubuntu-toolchain-r/test state=present validate_certs=no
  
- name: install GCC 4.9
  when: ansible_os_family == "Debian"
  apt: update_cache=yes name={{ item }} state=present
  with_items:
    - gcc-4.9
    - g++-4.9
